---
- name: Create vCenter VMs
  hosts: localhost 
  become: false
  gather_facts: false
  collections: 
    - community.vmware
    
  pre_tasks:
      - include_vars: vars.yml
      
  tasks:
  - name: Create folder
    community.vmware.vcenter_folder:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: "{{ vcenter_validate_certs }}"
      datacenter_name: "{{ vcenter_datacenter }}"
      folder_name: "{{ vcenter_destination_folder }}"
      folder_type: vm
      state: present

  - name: Create a virtual machine from a template
    community.vmware.vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      esxi_hostname: "n-esx02.netlab.fhict.nl"
      resource_pool: PRO35 
      #cluster: "{{ vcenter_cluster }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      folder: "{{ vcenter_destination_folder }}"
      name: "{{ vm_name }}"
      state: present
      #template: "template"
      guest_id: "{{ vm_guestid }}"
      datacenter: "{{ vcenter_datacenter }}"
      disk: 
      - size_gb: "{{ vm_disk_gb }}"
        type: "{{ vm_disk_type }}"
        datastore: "{{ vm_disk_datastore }}"
      hardware:
        memory_mb: "{{ vm_hw_ram_mb }}"
        num_cpus: "{{ vm_hw_cpu_n }}"
        num_cpu_cores_per_socket: 1
        scsi: paravirtual
        hotadd_cpu: true
        hotremove_cpu: true
        hotadd_memory: false
        version: "12" # Hardware version of virtual machine
        boot_firmware: "efi"
      #cdrom:
        #- controller_number: 0
         # unit_number: 0
          #state: present
          #type: iso
          #iso_path: "[datastore1] livecd.iso"
      networks:
        - name: "{{ vm_net_name }}"
          connected: true
          type: dhcp
          
    delegate_to: localhost
    register: deploy
