---
- name: Create vCenter VMs
  hosts: localhost 
  become: false
  gather_facts: false
  collections: 
    - community.vmware
    
  pre_tasks:
      - include_vars: varsTempl.yml
      
  tasks:
  - name: Create a virtual machine from a template
    community.vmware.vmware_guest:
      hostname: "vcenter.netlab.fhict.nl" 
      datacenter: "Netlab-DC" 
      cluster: "NETLAB-Cluster" 
      resource_pool: "{{ user_resourcepool }}"     
      #esxi_hostname: "n-esx02.netlab.fhict.nl"

      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      
      name: "{{ vm_name }}"
      folder: "{{ vcenter_destination_folder }}"
      template: "Templ_Ubuntu-Linux_Server_22.04.1"
      datastore: "{{ vm_disk_datastore }}"
       
      state: present
      
      
  - name: Reconfigure VM
    community.vmware.vmware_guest:
      hostname: "vcenter.netlab.fhict.nl" 
      datacenter: "Netlab-DC" 
      cluster: "NETLAB-Cluster" 
      resource_pool: "{{ user_resourcepool }}" 

      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      
      folder: "{{ vcenter_destination_folder }}"
      name: "{{ vm_name }}"
      
      disk: 
      - size_gb: "{{ vm_disk_gb }}"
        type: "{{ vm_disk_type }}"
        #datastore: "{{ vm_disk_datastore }}"
        
      hardware:
        memory_mb: "{{ vm_hw_ram_mb }}"
        num_cpus: "{{ vm_hw_cpu_n }}"
        num_cpu_cores_per_socket: 1
        scsi: paravirtual
        hotadd_cpu: true
        hotremove_cpu: true
        hotadd_memory: false
        boot_firmware: "efi"
        
      networks:
        - name: "{{ vm_net_name }}"
          connected: true
          type: dhcp
      #wait_for_ip_address: true
      
      state: present

      
    delegate_to: localhost
    register: deploy
