- hosts: localhost
  connection: local
  tasks:
    - vsphere_guest:
            vcenter_hostname: vcenter.netlab.fhict.nl
            username: PRO35@fhict.nl
            password: Wmy4CqMXY
            guest: newvm001
            state: powered_on
            validate_certs: no
            vm_extra_config:
                vcpu.hotadd: yes
                mem.hotadd:  yes
                notes: This is a test VM
                folder: MyFolder
            vm_disk:
                disk1:
                        size_gb: 20
                        type: thin
                        datastore: DataCluster-Students
            vm_nic:
                nic1:
                    type: vmxnet3
                    network: 0308-STATIC-192.168.158.x_24
                    network_type: standard
            vm_hardware:
                memory_mb: 4096
                num_cpus: 2
                osid: ubuntu64Guest
                scsi: paravirtual
            esxi:
                datacenter: n-esx07.netlab.fhict.nl
                hostname: n-esx07.netlab.fhict.nl